version: '3'
services:

  rabbitmq:
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
    image: bitnami/rabbitmq:3.8.2
    logging:
      driver: awslogs
      options:
        awslogs-group: senzing-docker-compose-aws-ecscli-demo-rabbitmq
        awslogs-region: us-east-1
        awslogs-stream-prefix: web
    ports:
      - 80:15672
      - 5672:5672
