version: '3'
services:
  efsinitcontainer:
    command:
      - mkdir
      - /efs/g2
      - "&&"
      - mkdir
      - -p
      - /efs/data/2.0.0
      - "&&"
      - mkdir
      - /efs/etc
      - "&&"
      - mkdir
      - /efs/var
    image: busybox
    logging:
      driver: awslogs
      options:
        awslogs-group: ${SENZING_AWS_LOGS_GROUP:-senzing-docker-compose-aws-ecscli-demo}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: advanced-cluster
    user: ${SENZING_DOCKER_RUNAS_INIT_EFS}
    volumes:
      - senzing-efs-root:/efs
volumes:
  senzing-efs-root:
