version: '3'
services:
  apiserver:
    command:
      - -httpPort
      - "8250"
      - -bindAddr
      - all
      - -iniFile
      - /etc/opt/senzing/G2Module.ini
      - -allowedOrigins
      - "*"
      - -initEnvVar
      - SENZING_ENGINE_CONFIGURATION_JSON
    environment:
      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST}:5432/${POSTGRES_DB:-G2}"
      SENZING_ENGINE_CONFIGURATION_JSON: >-
        {
          "PIPELINE": {
            "CONFIGPATH": "/etc/opt/senzing",
            "RESOURCEPATH": "/opt/senzing/g2/resources",
            "SUPPORTPATH": "/opt/senzing/data"
          },
          "SQL": {
            "BACKEND": "HYBRID",
            "CONNECTION": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST}:5432:${POSTGRES_DB:-G2}"
          },
          "C1": {
            "CLUSTER_SIZE": "1",
            "DB_1": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST_RES}:5432:${POSTGRES_DB:-G2_RES}"
          },
          "C2": {
            "CLUSTER_SIZE": "1",
            "DB_1": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST_LIBFEAT}:5432:${POSTGRES_DB:-G2_LIBFEAT}"
          },
          "HYBRID": {
            "RES_FEAT": "C1",
            "RES_FEAT_EKEY": "C1",
            "RES_FEAT_LKEY": "C1",
            "RES_FEAT_STAT": "C1",
            "LIB_FEAT": "C2",
            "LIB_FEAT_HKEY": "C2"
          }
        }
    image: senzing/senzing-api-server:${SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER:-2.3.0}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${SENZING_AWS_LOGS_GROUP:-senzing-docker-compose-aws-ecscli-demo}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: advanced-cluster
    ports:
      - 8250:8250
    user: ${SENZING_DOCKER_RUNAS_SENZING_API_SERVER}
    volumes:
      - senzing-data-version-dir:/opt/senzing/data
      - senzing-etc-dir:/etc/opt/senzing
      - senzing-g2-dir:/opt/senzing/g2
volumes:
  senzing-data-version-dir:
  senzing-etc-dir:
  senzing-g2-dir:
