version: '3'
services:
  producer:
    environment:
      SENZING_DELAY_IN_SECONDS: 60
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_RABBITMQ_HOST: ${SENZING_EC2_HOST}
      SENZING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
      SENZING_RABBITMQ_QUEUE: senzing-rabbitmq-queue
      SENZING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
      SENZING_RECORD_MAX: 5000
      SENZING_RECORD_MONITOR: 1000
      SENZING_SUBCOMMAND: json-to-rabbitmq
    image: senzing/stream-producer:${SENZING_STREAM_PRODUCER_VERSION:-1.1.1}
    logging:
      driver: awslogs
      options:
        awslogs-group: senzing-docker-compose-aws-ecscli-demo
        awslogs-region: us-east-1
        awslogs-stream-prefix: beginner-rabbitmq
