version: '3'
services:
  efsinitcontainer:
    command:
      - mkdir
      - /efs/g2
      - "&&"
      - mkdir
      - -p
      - /efs/data/1.0.0
      - "&&"
      - mkdir
      - /efs/etc
      - "&&"
      - mkdir
      - /efs/var
    image: busybox
    logging:
      driver: awslogs
      options:
        awslogs-group: senzing-docker-compose-aws-ecscli-demo
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: advanced
    volumes:
      - senzing-efs-root:/efs
volumes:
  senzing-efs-root:
