version: '3'
services:
  apiserver:
    command:
      - -httpPort
      - "8250"
      - -bindAddr
      - all
      - -iniFile
      - /etc/opt/senzing/G2Module.ini
      - -allowedOrigins
      - "*"
    environment:
      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST}:5432/${POSTGRES_DB:-G2}"
    image: senzing/senzing-api-server:${SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER:-2.6.1}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${SENZING_AWS_LOGS_GROUP:-senzing-docker-compose-aws-ecscli-demo}
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-stream-prefix: advanced
    ports:
      - 8250:8250
    user: ${SENZING_DOCKER_RUNAS_SENZING_API_SERVER}
    volumes:
      - senzing-data-version-dir:/opt/senzing/data
      - senzing-etc-dir:/etc/opt/senzing
      - senzing-g2-dir:/opt/senzing/g2
volumes:
  senzing-data-version-dir:
  senzing-etc-dir:
  senzing-g2-dir:
