version: '3'
services:
  producer:
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_METADATA_SERVICE_NUM_ATTEMPTS: ${AWS_METADATA_SERVICE_NUM_ATTEMPTS:-1}
      AWS_METADATA_SERVICE_TIMEOUT: ${AWS_METADATA_SERVICE_TIMEOUT:-1}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_RECORD_MAX: 5000
      SENZING_RECORD_MONITOR: 1000
      SENZING_SQS_QUEUE_URL: ${SENZING_SQS_QUEUE_URL}
      SENZING_SUBCOMMAND: json-to-sqs
    image: senzing/stream-producer:${SENZING_DOCKER_IMAGE_VERSION_STREAM_PRODUCER:-1.3.2}
    logging:
      driver: awslogs
      options:
        awslogs-group: senzing-docker-compose-aws-ecscli-demo
        awslogs-region: us-east-1
        awslogs-stream-prefix: intermediate
