version: '3'
services:
  efsinitcontainer:
    command:
      - mkdir
      - /efs/g2
      - "&&"
      - mkdir
      - /efs/data
      - "&&"
      - mkdir
      - /efs/etc
      - "&&"
      - mkdir
      - /efs/var
    image: busybox
    logging:
      driver: awslogs
      options:
        awslogs-group: senzing-docker-compose-aws-ecscli-demo
        awslogs-region: us-east-1
        awslogs-stream-prefix: intermediate
    volumes:
      - senzing-efs-root:/efs
volumes:
  senzing-efs-root:
